#!/usr/bin/env python3
"""Generate the MacPorts `cargo.crates` block from Cargo.lock.

MacPorts builds Rust ports offline. The cargo PortGroup passes `--frozen` and
replaces crates.io with a local directory, so every crate cargo will resolve
has to be declared in the Portfile as a `name version sha256` triple. MacPorts
fetches each one from `https://static.crates.io/crates/<name>/<name>-<version>.crate`
and verifies the checksum before the build phase starts.

That list is the whole Cargo.lock, so it changes on every dependency bump and
must never be edited by hand. Run this script instead:

    # print the block
    packaging/macports/gen-crates.py

    # rewrite the block inside the Portfile in place
    packaging/macports/gen-crates.py --update packaging/macports/Portfile

The Portfile marks the generated region with BEGIN/END comments; `--update`
replaces everything between them and leaves the rest of the file alone.

MacPorts ships its own generator (`port install cargo2port`), which produces the
same output. This one is in-tree so the list can be refreshed from a checkout
with nothing but Python installed, and so CI can assert the Portfile is current.

Exit status with `--check`: 0 if the Portfile's block already matches Cargo.lock,
1 if it is stale.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

BEGIN = "# BEGIN cargo.crates -- generated by packaging/macports/gen-crates.py"
END = "# END cargo.crates"

REPO_ROOT = Path(__file__).resolve().parents[2]

# A `[[package]]` stanza in Cargo.lock. Workspace members have no `source`, and
# a crate that is not on crates.io has no `checksum`; both are filtered out
# below rather than matched here, so a non-crates.io source is reported as an
# error instead of silently dropped.
PACKAGE_RE = re.compile(
    r'^name = "(?P<name>[^"]+)"\n'
    r'version = "(?P<version>[^"]+)"\n'
    r'(?:source = "(?P<source>[^"]+)"\n)?'
    r'(?:checksum = "(?P<checksum>[^"]+)"\n)?',
    re.MULTILINE,
)

CRATES_IO = "registry+https://github.com/rust-lang/crates.io-index"


def read_crates(lockfile: Path) -> list[tuple[str, str, str]]:
    """Return every crates.io dependency in `lockfile` as (name, version, sha256).

    Workspace members (no `source`) are skipped: they are the port's own source,
    not something MacPorts fetches. Anything else without a crates.io source is
    a hard error, because the cargo PortGroup needs `cargo.crates_github`
    5-tuples for those and this script does not emit them.
    """
    text = lockfile.read_text(encoding="utf-8")
    crates: list[tuple[str, str, str]] = []
    foreign: list[str] = []

    for stanza in text.split("[[package]]")[1:]:
        match = PACKAGE_RE.search(stanza.lstrip("\n"))
        if match is None:
            raise SystemExit(f"could not parse a [[package]] stanza in {lockfile}")
        name = match.group("name")
        version = match.group("version")
        source = match.group("source")
        checksum = match.group("checksum")

        if source is None:
            # A workspace member: engramdb, engram-cli, engram-types, ...
            continue
        if source != CRATES_IO or checksum is None:
            foreign.append(f"{name} {version} ({source})")
            continue
        crates.append((name, version, checksum))

    if foreign:
        raise SystemExit(
            "these dependencies are not plain crates.io crates, so the Portfile "
            "needs a hand-written cargo.crates_github entry for each:\n  "
            + "\n  ".join(foreign)
        )

    # Sort so an unrelated Cargo.lock reordering does not churn the Portfile.
    # Duplicate names with different versions are normal in this tree (the
    # arrow / datafusion / ort stack pulls several), so sort on the pair.
    crates.sort(key=lambda c: (c[0], c[1]))
    return crates


def render(crates: list[tuple[str, str, str]]) -> str:
    """Render the crates as a MacPorts `cargo.crates` continuation block."""
    name_width = max(len(name) for name, _, _ in crates)
    version_width = max(len(version) for _, version, _ in crates)

    lines = [BEGIN, "cargo.crates \\"]
    for index, (name, version, checksum) in enumerate(crates):
        last = index == len(crates) - 1
        continuation = "" if last else " \\"
        # Name left-aligned, version right-aligned, as `cargo2port` renders it.
        lines.append(
            f"    {name:<{name_width}}  {version:>{version_width}}  {checksum}{continuation}"
        )
    lines.append(END)
    return "\n".join(lines) + "\n"


def splice(portfile_text: str, block: str) -> str:
    """Replace the BEGIN/END region of `portfile_text` with `block`."""
    start = portfile_text.find(BEGIN)
    end = portfile_text.find(END)
    if start == -1 or end == -1:
        raise SystemExit(
            f"the Portfile has no generated region; it must contain a line\n"
            f"  {BEGIN}\n"
            f"and a later line\n"
            f"  {END}"
        )
    if end < start:
        raise SystemExit("the Portfile's END marker precedes its BEGIN marker")
    return portfile_text[:start] + block + portfile_text[end + len(END) + 1 :]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--lockfile",
        type=Path,
        default=REPO_ROOT / "Cargo.lock",
        help="Cargo.lock to read (default: the workspace root's)",
    )
    parser.add_argument(
        "--update",
        type=Path,
        metavar="PORTFILE",
        help="rewrite the generated region of PORTFILE in place",
    )
    parser.add_argument(
        "--check",
        type=Path,
        metavar="PORTFILE",
        help="exit non-zero if PORTFILE's generated region is out of date",
    )
    args = parser.parse_args()

    crates = read_crates(args.lockfile)
    block = render(crates)

    target = args.update or args.check
    if target is None:
        sys.stdout.write(block)
        return 0

    text = target.read_text(encoding="utf-8")
    updated = splice(text, block)

    if args.check:
        if updated != text:
            print(
                f"{target} is out of date with {args.lockfile}; "
                f"run packaging/macports/gen-crates.py --update {target}",
                file=sys.stderr,
            )
            return 1
        print(f"{target} matches {args.lockfile} ({len(crates)} crates)")
        return 0

    if updated == text:
        print(f"{target} already current ({len(crates)} crates)")
    else:
        target.write_text(updated, encoding="utf-8")
        print(f"{target} updated ({len(crates)} crates)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
